# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"

env:
    - DJANGO="Django==1.8"
    - DJANGO="Django==1.9"
    - DJANGO="Django==1.10"

matrix:
    exclude:
        # Python 3.3 support has been dropped in Django 1.9
        - python: "3.3"
          env: DJANGO="Django==1.9"
        - python: "3.3"
          env: DJANGO="Django==1.10"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
 - pip install $DJANGO
 - pip install -r requirements-test.txt

# command to run tests using coverage, e.g. python setup.py test
script: coverage run --source responsive runtests.py

# report coverage to coveralls.io
after_success: coveralls
